# Generated by Django 6.0.1 on 2026-01-18 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterModelOptions(
            name='historicalcandidate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Кандидат', 'verbose_name_plural': 'historical Кандидаты'},
        ),
        migrations.AlterModelOptions(
            name='historicalnomination',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Номинация', 'verbose_name_plural': 'historical Номинации'},
        ),
        migrations.AlterModelOptions(
            name='historicalvote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Голос', 'verbose_name_plural': 'historical Голоса'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name': 'Номинация', 'verbose_name_plural': 'Номинации'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя кандидата'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nomination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='polls.nomination', verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя кандидата'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='nomination',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='polls.nomination', verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='historicalnomination',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalnomination',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='historicalnomination',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название номинации'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='candidate',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='polls.candidate', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата голосования'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название номинации'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.candidate', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата голосования'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя члена жюри')),
                ('nominations', models.ManyToManyField(blank=True, related_name='jury_members', to='polls.nomination', verbose_name='Номинации')),
            ],
            options={
                'verbose_name': 'Член жюри',
                'verbose_name_plural': 'Жюри',
            },
        ),
    ]
