# Generated by Django 6.0.1 on 2026-01-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomination',
            options={'ordering': ['-created_at'], 'verbose_name': 'Номинация', 'verbose_name_plural': 'Номинации'},
        ),
    ]
